# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stack1.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def clicked_back(self, nd):
        print("click : go back")
        MainWindow.pageX =- 1
    def clicked(self):
        print(MainWindow.pageX)
        print("click : go Next")
        MainWindow.pageX =+ 1
        print(MainWindow.pageX)

        self.stackedWidget.setCurrentIndex(MainWindow.pageX)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 479)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 641, 441))
        self.stackedWidget.setObjectName("stackedWidget")

        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")

        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(0, 20, 631, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.b1 = QtWidgets.QPushButton(self.page)
        self. b1.setGeometry(QtCore.QRect(480, 370, 151, 61))
        self.b1.setObjectName("pushButton")
        self.b1.setText("X")

        self.b1.clicked.connect(self.clicked)


        self.stackedWidget.addWidget(self.page)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")

        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 641, 421))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("02.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        MainWindow.pageX = 0
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(MainWindow.pageX) #<------ จะเปลี่ยนหน้าจอที่แสดง ต้องเขียน Event ให้มาเปลี่ยนค่าตรงนี้

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
       # self.pushButton.setText(_translate("MainWindow", "PushButton z"))
        self.b1.setText(_translate("MainWindow", "PushButton z"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
